### PR TITLE
Create an Algebra microsite

### PR DESCRIPTION
**Pull request by sritchie**
This PR creates a microsite for Algebra. To that end it:

- moves the tour of its algebraic structures out of the README and into the microsite
- adds a `CONTRIBUTING.md` page
- adds an empty `CHANGELOG.md`, which we should start using!
- struts out the site without adding much structure or documentation. I'll need input from the committers on that.
- publishes all scaladocs to `/api` under the microsite

### CODE REVIEW

**Comment by sritchie** [comment]
We'll also want to add the microsite URL to the github description.

**Comment by johnynek** [comment]
👍 looks good to me at a quick glance. Any example of the microsite? Should we check out the branch and build it (also happy to iterate on the main site).

**Comment by sritchie** [comment]
Let me push the microsite example now, one sec

**Comment by sritchie** [comment]
Live at https://sritchie.github.io/algebra! I didn't push a version with these changes:

https://github.com/typelevel/algebra/pull/193/commits/20e02364900540205da260fedbc2f8e877e2ae86

So just note that  `quot` and `EuclideanRing` are no longer mentioned.

**Comment by sritchie** [comment]
@tixxit @johnynek merge?

**Pull request merged**
