### PR TITLE
Upgrade to Cats 0.9.0.

### PR DESCRIPTION
**Pull request by non**
This also upgrades to Scala.js 0.6.14.

### CODE REVIEW

**Comment by johnynek** [comment]
What are you doing up?

**Comment by non** [comment]
Haha, I just realized that I had said I'd start the release process, so wanted to push it along before bed.

**Comment by johnynek** [comment]
:+1:

**Comment by non** [comment]
Great! Assuming things go green I'll merge and release (and then go to sleep).

**Comment by johnynek** [comment]
Sounds good. Sleep well!

**Comment by non** [comment]
Property failure:

```
[info] - [algebra.laws.Rat].field.fromDouble *** FAILED ***
[info]   GeneratorDrivenPropertyCheckFailedException was thrown during property evaluation.
[info]    (Discipline.scala:14)
[info]     Falsified after 4 successful property evaluations.
[info]     Location: (Discipline.scala:14)
[info]     Occurred when passed generated values (
[info]       arg0 = 1.9726888167225064E-308
[info]     )
[info]     Label of failing property:
[info]       (2124091560789543/101201126653655309176247673359458653524778324882071059178450679013715169783997673445980191850718562247593538932158405955694904368692896738433506699970369254960758712138283180682233453871046608170619883839236372534281003741712346349309051677824579778170405028256179384776166707307615251266093163754323003131653853870546747392 ?== 998191653946919/50600563326827654588123836679729326762389162441035529589225339506857584891998836722990095925359281123796769466079202977847452184346448369216753349985184627480379356069141590341116726935523304085309941919618186267140501870856173174654525838912289889085202514128089692388083353653807625633046581877161501565826926935273373696) failed
```

**Comment by johnynek** [comment]
Is that Scala.js or Scala?

**Comment by non** [comment]
It's on the JVM, we skip that test in Scala.js.

**Comment by johnynek** [comment]
They fixed that bug I thought? (In scala.js)

**Comment by non** [comment]
It seems like this is a legit bug:

```scala
val x = Field[Rat].fromDouble(1.9726888167225064E-308)
BigDecimal(x.num) / BigDecimal(x.den) // 2.098881337614853913158104485839156E-308
```

**Comment by non** [comment]
/cc @tixxit 

I'm fine with opening an issue for this, merging this PR, and releasing. But if it's easy to fix it would be nice to do so first.

**Comment by non** [comment]
I think the bug here is in handling *sub-normal* floating point values. `e-307` and above seem fine, but `e-308` and below (towards zero) have problems.

**Comment by tixxit** [comment]
Hrmmm - I thought I had handled the case where the implicit 1 drops when exp bits are 0, but maybe not? I'll take a look and see if I can fix it up quickly.

**Comment by tixxit** [comment]
Alright - I got a fix incoming. I'll push to this branch.

**Comment by johnynek** [comment]
👍 

I guess we can merge? Since Three of us seem in agreement?

**Pull request merged**
