### PR TITLE
Scala 2.12: updated to cats 0.8.1 and shadowed its dependencies.

### PR DESCRIPTION
**Pull request by denisrosset**
Everything is basically in the title!

...except the `Order` that depends on the generation of `A => A`, which should be updated to use a `Cogen[A]`.

### CODE REVIEW

**Comment by tixxit** [comment]
@denisrosset If we merge #182 first, then we won't have to worry about the `Order` test.

**Comment by thomas-stripe** [comment]
@denisrosset OK, #182 got merged, so we just use cats-kernel's `OrderLaws`. Want to merge master?

**Comment by denisrosset** [comment]
Merged and bug fixed.

**Comment by johnynek** [comment]
👍

**Pull request merged**
