### PR TITLE
Scala 2.13.0-M4

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by andyscott** [comment]
Looks like the test failed because of Travis flakiness. Any chance we could have the tests re-run and if they pass have a release cut with 2.13.-M4 support?

**Comment by larsrh** [comment]
@andyscott I've restarted the builds. Maybe if this one works, we can update to M5 quickly.

**Comment by LukaJCB** [comment]
:+1:

**Comment by larsrh** [comment]
Sorry for dropping the ball on this. algebra is now needed for cats-collections, so I'm going to resume working on a release.

**Pull request merged**
