### PR TITLE
Bump ScalaCheck to 1.13.0

### PR DESCRIPTION
**Pull request by adelbertc**
Pending non-SNAPSHOT release of https://github.com/scalatest/scalatest/issues/837 and https://github.com/typelevel/discipline/pull/17

### CODE REVIEW

**Comment by adelbertc** [comment]
How do folks feel about depending on a SNAP release (effectively a stable SNAPSHOT if I understand correctly) for ScalaCheck? Discipline has it merged: https://github.com/typelevel/discipline/pull/17#issuecomment-208167297 

Or we can wait for a final release: https://github.com/scalatest/scalatest/issues/837#issuecomment-200549889

**Comment by kailuowang** [comment]
As a user, I vote for depending on the SNAP release of ScalaCheck.

**Comment by johnynek** [comment]
-1 on SNAP. Can we not do that?

**Comment by adelbertc** [comment]
Yeah we can just wait for a stable one to be cut,  mostly made this to help
me track in progress things

**Comment by BennyHill** [comment]
Looks like it should now be 1.13.2, as in https://github.com/typelevel/cats/pull/1345

Also, :

```sbt
 "org.scalacheck" %%% "scalacheck" % "1.13.2",
 "org.typelevel" %%% "discipline" % "0.7",
 "org.scalatest" %%% "scalatest" % "3.0.0" % "test"
```

In return, you may find you get 2.12.0-RC1 coming your way pretty soon. 

( you will also need https://github.com/typelevel/catalysts/issues/2 - and that's itching to go :smile: )

**Comment by denisrosset** [comment]
This can be closed as it is super-ceded by #184

**Pull request closed without merging**
