### PR TITLE
Experimental update to cats 1.0.0-RC1

### PR DESCRIPTION
**Pull request by denisrosset**
As I'm moving Spire to cats 1.0.0-RC1, I needed a quick'n'dirty version of algebra that would be compatible.

This is it. I upgraded the plugins and dependencies, and copied the kernel-laws old style source code in algebra as a temporary measure until the test suite is upgraded.

### CODE REVIEW

**Comment by johnynek** [comment]
I thought this was red, but it looks like it may just be mima.

Do you want to disable mima for the laws until we get this green?

**Comment by SethTisue** [comment]
I'm interested in seeing this upgrade cross the finish line, because I'm trying to upgrade the Scala 2.12 community build to cats 1.0 (over at https://github.com/scala/community-builds/issues/653), and algebra is one of the few remaining blockers for that.

**Comment by johnynek** [comment]
@SethTisue yeah, sorry... We need to regroup and get it down. We'll do it. cc @non

**Comment by johnynek** [comment]
@denisrosset it looks like this passed except for mima. Do you want to remove mima from the travis check here: https://github.com/typelevel/algebra/blob/master/.travis.yml#L41 and bump to cats 1.0.1 and we can merge and publish?

**Comment by coltfred** [comment]
@johnynek @denisrosset -- Poke.

I'm coming up on needing spire for cats 1.x and this is the first step to that.

**Comment by johnynek** [comment]
@coltfred we just need to disable mima check, be sure tests pass, I'll merge, anyone at typelevel can publish (including me, but maybe also you?)....

I'll try to take some time soon, but I'm really underwater at the moment.

**Comment by coltfred** [comment]
@johnynek I have no problem publishing once we're ready to do that, but I'm headed out and will be without internet for a week and I'm hoping it'll be done before I get back. :)

@stephen-lazaro If you want to take a crack at disabling mima and ensuring the tests pass with these changes we can start moving forward with spire.

**Comment by stephen-lazaro** [comment]
Sounds good! If I'm not stepping on anyone's toes I'll figure it out a solution this weekend.

**Comment by vpavkin** [comment]
Hello all!
Created a PR with mima disabled and cats bumped to 1.0.1: #213.

Hope this helps.

**Pull request closed without merging**
