### PR TITLE
Update to Cats 1.0.1

### PR DESCRIPTION
**Pull request by vpavkin**
My attempt to continue progress on #207.

@johnynek is this all we need ? :)

### CODE REVIEW

**Comment by vpavkin** [comment]
@denisrosset @johnynek this is green now, what's my next step (if there's any)?

**Comment by johnynek** [comment]
next step is to publish, let me try....

**Comment by johnynek** [comment]
Thank you!

**Comment by johnynek** [comment]
I tried to publish this but hit some confusing sbt/release/sonatype etc... errors:

```
[info]   Evaluate: signature-staging
[error] Failed to close the repository
[error] Activity close started:2018-02-15T20:33:56.111Z, stopped:
[error]     Failed: sources-staging, failureMessage:Illegal POM: /org/typelevel/algebra_2.11/1.0.0/algebra_2.11-1.0.0.pom Duplicated tag: 'scm' (position: START_TAG
seen ...&lt;/scm>\n    &lt;scm>... @27:10)
[error]     Failed: javadoc-staging, failureMessage:Illegal POM: /org/typelevel/algebra_2.11/1.0.0/algebra_2.11-1.0.0.pom Duplicated tag: 'scm' (position: START_TAG
seen ...&lt;/scm>\n    &lt;scm>... @27:10)
java.lang.Exception: Failed to close the repository
        at xerial.sbt.Sonatype$NexusRESTService.closeStage(Sonatype.scala:721)
        at xerial.sbt.Sonatype$NexusRESTService.closeAndPromote(Sonatype.scala:820)
        at xerial.sbt.Sonatype$SonatypeCommand$$anonfun$22$$anonfun$apply$11.apply(Sonatype.scala:215)
        at xerial.sbt.Sonatype$SonatypeCommand$$anonfun$22$$anonfun$apply$11.apply(Sonatype.scala:214)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
```

I am going to try to get #212 merged and maybe that will fix it. Any one who knows sbt or sbt-release and can help fix would be great.

**Comment by ryan-williams** [comment]
Lightly interpreting the error msg: it's failing a POM validation because the `<scm>` tag appears twice. I can reproduce that locally after running `publishLocal` in this repo.

**Comment by johnynek** [comment]
yeah, but I dont see the `<scm>` twice in the config. I have a vague memory of working around this in the past, but I don't recall the solution.

@gkk-stripe do you know how to fix?

**Comment by ryan-williams** [comment]
yea, weird, I have to slightly walk back my claim about a `publishLocal` repro. I ran `publishLocal` on this PR's branch last night to do some testing against a spire that used it, and when you posted your error I checked and those POMs had two `<scm>` tags, but now I can't reproduce that! Will lyk if I find a clue.

**Comment by coltfred** [comment]
@johnynek I assume you must not have been able to get it published, still? I'm in an airport (back on the internet, finally), but I can't publish from here. @denisrosset, do you happen to have any ideas on the SCM issue?

**Comment by johnynek** [comment]
Yeah I haven’t been able to diagnose the scm issue. I don’t recall how I got past it before. I think I complained about sbt until someone who thinks it is good fixed it. I was kind of hoping to do the same here.

**Comment by andyscott** [comment]
@johnynek Want me to take a look at this this week?

**Comment by coltfred** [comment]
@johnynek published version should be 1.0, correct?

**Comment by tpolecat** [comment]
Yeah this change happened when I updated to sbt 1.0 … have you done a release since then? I also updated a bunch of plugins so I'm not sure what exactly triggered it but I guess it doesn't matter. The commit where I finally fixed it has the comment "ffs" so I was pretty unhappy by that point.

**Comment by johnynek** [comment]
I tried commenting out the scm but from the pomInfo but didn’t seem to work. Maybe I forgot to reload in my frustration. I’ll try again.

**Comment by denisrosset** [comment]
@vpavkin thanks for picking that stuff! I'm pretty much under water right now, so it's good that this progresses.

**Pull request merged**
